### ISSUE TITLE
Could use filter in question one solution two?

### ISSUE THREAD

**Issue by danielctull** [LemonSpike/SwiftAlgorithmsNSLondon#1]
It seems like [solution two](https://github.com/LemonSpike/SwiftAlgorithmsNSLondon/blob/1b110ffd789926e4a27678a6f9332b43a5236a15/Sources/SwiftAlgorithmsAsAPackage/QuestionOne/QOneSolutionTwo.swift#L12) would be more readable if it were to use filter? 

``` swift
struct QOneSolutionTwo {
  func fourSum(_ numbers: [Int], target: Int) -> Set<Set<Int>> {

    let result = numbers
      .combinations(ofCount: 4)
      .filter { $0.reduce(0, +) == target }
      .map(Set.init)

    return Set(result)
  }
}
```

In the first solution you used `[[Int]]` and in the second you used `Set<Set<Int>>` is this to show some performance improvement here? I assumed the project is demonstrating the use of [swift-algorithms](https://github.com/apple/swift-algorithms), and as such perhaps this change from arrays to sets muddies the water? If you maintained the same return type for solution two it would simply be the following and nicely demonstrate why having an algorithms package is useful.

``` swift
struct QOneSolutionTwo {
  func fourSum(_ numbers: [Int], target: Int) -> [[Int]] {

    numbers
      .combinations(ofCount: 4)
      .filter { $0.reduce(0, +) == target }
  }
}
```

**Comment by LemonSpike** [comment]
Thanks @danielctull, great suggestion! I've added a new commit that makes the answer clearer for kSum.
